CC=gcc
CFLAGS=-m32 -c -Wall -I"../Open Steamworks" -I"../boost_1_40_0" -fshort-enums -Wfatal-errors
LDFLAGS=-m32 -lstdc++ -Wl,-R./ -L./ steamclient_linux.so
SOURCES=main.cpp util.cpp CItemDB.cpp FileLogger.cpp CUser.cpp CClientContext.cpp CServerContext.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=idler2

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@