// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSStatsReceived_t
	{
		EResult m_eResult;
		UInt64 m_steamIDUser;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSStatsStored_t
	{
		EResult m_eResult;
		UInt64 m_steamIDUser;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSStatsUnloaded_t
	{
		UInt64 m_steamIDUser;
	};
	
}
