// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSItemCount_t
	{
		UInt64 m_steamID;
		EItemRequestResult m_eResult;
		UInt32 m_unCount;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSItemRequest_t
	{
		UInt64 m_steamID;
		EItemRequestResult m_eResult;
		UInt64 m_itemID;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSItemGranted_t
	{
		UInt64 m_steamID;
		UInt64 m_itemID;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSItemGetBlob_t
	{
		UInt64 m_itemID;
		EItemRequestResult m_eResult;
		[MarshalAs(UnmanagedType.ByValArray, SizeConst = 1024)]
		Byte[] m_itemBlob;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct GSItemSetBlob_t
	{
		UInt64 m_itemID;
		EItemRequestResult m_eResult;
		UInt32 Unk;
	};
	
}
