// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	public enum EHTTPMethod : int
	{
		k_EHTTPMethodInvalid = 0,
		k_EHTTPMethodGET = 1,
		k_EHTTPMethodHEAD = 2,
		k_EHTTPMethodPOST = 3,
	};
	
	public enum EHTTPStatusCode : int
	{
		k_EHTTPStatusCodeInvalid = 0,
		k_EHTTPStatusCode100Continue = 100,
		k_EHTTPStatusCode101SwitchingProtocols = 101,
		k_EHTTPStatusCode200OK = 200,
		k_EHTTPStatusCode201Created = 201,
		k_EHTTPStatusCode202Accepted = 202,
		k_EHTTPStatusCode203NonAuthoritative = 203,
		k_EHTTPStatusCode204NoContent = 204,
		k_EHTTPStatusCode205ResetContent = 205,
		k_EHTTPStatusCode206PartialContent = 206,
		k_EHTTPStatusCode300MultipleChoices = 300,
		k_EHTTPStatusCode301MovedPermanently = 301,
		k_EHTTPStatusCode302Found = 302,
		k_EHTTPStatusCode303SeeOther = 303,
		k_EHTTPStatusCode304NotModified = 304,
		k_EHTTPStatusCode305UseProxy = 305,
		k_EHTTPStatusCode307TemporaryRedirect = 307,
		k_EHTTPStatusCode400BadRequest = 400,
		k_EHTTPStatusCode401Unauthorized = 401,
		k_EHTTPStatusCode402PaymentRequired = 402,
		k_EHTTPStatusCode403Forbidden = 403,
		k_EHTTPStatusCode404NotFound = 404,
		k_EHTTPStatusCode405MethodNotAllowed = 405,
		k_EHTTPStatusCode406NotAcceptable = 406,
		k_EHTTPStatusCode407ProxyAuthRequired = 407,
		k_EHTTPStatusCode408RequestTimeout = 408,
		k_EHTTPStatusCode409Conflict = 409,
		k_EHTTPStatusCode410Gone = 410,
		k_EHTTPStatusCode411LengthRequired = 411,
		k_EHTTPStatusCode412PreconditionFailed = 412,
		k_EHTTPStatusCode413RequestEntityTooLarge = 413,
		k_EHTTPStatusCode414RequestURITooLong = 414,
		k_EHTTPStatusCode415UnsupportedMediaType = 415,
		k_EHTTPStatusCode416RequestedRangeNotSatisfiable = 416,
		k_EHTTPStatusCode417ExpectationFailed = 417,
		k_EHTTPStatusCode500InternalServerError = 500,
		k_EHTTPStatusCode501NotImplemented = 501,
		k_EHTTPStatusCode502BadGateway = 502,
		k_EHTTPStatusCode503ServiceUnavailable = 503,
		k_EHTTPStatusCode504GatewayTimeout = 504,
		k_EHTTPStatusCode505HTTPVersionNotSupported = 505,
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class IClientHTTPVTable
	{
		public IntPtr CreateHTTPRequest0;
		public IntPtr SetHTTPRequestContextValue1;
		public IntPtr SetHTTPRequestNetworkActivityTimeout2;
		public IntPtr SetHTTPRequestHeaderValue3;
		public IntPtr SetHTTPRequestGetOrPostParameter4;
		public IntPtr SendHTTPRequest5;
		public IntPtr DeferHTTPRequest6;
		public IntPtr PrioritizeHTTPRequest7;
		public IntPtr GetHTTPResponseHeaderSize8;
		public IntPtr GetHTTPResponseHeaderValue9;
		public IntPtr GetHTTPResponseBodySize10;
		public IntPtr GetHTTPResponseBodyData11;
		public IntPtr ReleaseHTTPRequest12;
		private IntPtr DTorIClientHTTP13;
	};
	
	public class IClientHTTP : InteropHelp.NativeWrapper<IClientHTTPVTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeCreateHTTPRequestES( IntPtr thisptr, EHTTPMethod eHTTPRequestMethod, StringBuilder pchAbsoluteURL );
		public UInt32 CreateHTTPRequest( EHTTPMethod eHTTPRequestMethod, StringBuilder pchAbsoluteURL ) 
		{
			return this.GetFunction<NativeCreateHTTPRequestES>( this.Functions.CreateHTTPRequest0 )( this.ObjectAddress, eHTTPRequestMethod, pchAbsoluteURL ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetHTTPRequestContextValueUU( IntPtr thisptr, UInt32 hRequest, UInt64 ulContextValue );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool SetHTTPRequestContextValue( UInt32 hRequest, UInt64 ulContextValue ) 
		{
			return this.GetFunction<NativeSetHTTPRequestContextValueUU>( this.Functions.SetHTTPRequestContextValue1 )( this.ObjectAddress, hRequest, ulContextValue ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetHTTPRequestNetworkActivityTimeoutUU( IntPtr thisptr, UInt32 hRequest, UInt32 unTimeoutSeconds );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool SetHTTPRequestNetworkActivityTimeout( UInt32 hRequest, UInt32 unTimeoutSeconds ) 
		{
			return this.GetFunction<NativeSetHTTPRequestNetworkActivityTimeoutUU>( this.Functions.SetHTTPRequestNetworkActivityTimeout2 )( this.ObjectAddress, hRequest, unTimeoutSeconds ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetHTTPRequestHeaderValueUSS( IntPtr thisptr, UInt32 hRequest, StringBuilder pchHeaderName, StringBuilder pchHeaderValue );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool SetHTTPRequestHeaderValue( UInt32 hRequest, StringBuilder pchHeaderName, StringBuilder pchHeaderValue ) 
		{
			return this.GetFunction<NativeSetHTTPRequestHeaderValueUSS>( this.Functions.SetHTTPRequestHeaderValue3 )( this.ObjectAddress, hRequest, pchHeaderName, pchHeaderValue ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetHTTPRequestGetOrPostParameterUSS( IntPtr thisptr, UInt32 hRequest, StringBuilder pchParamName, StringBuilder pchParamValue );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool SetHTTPRequestGetOrPostParameter( UInt32 hRequest, StringBuilder pchParamName, StringBuilder pchParamValue ) 
		{
			return this.GetFunction<NativeSetHTTPRequestGetOrPostParameterUSS>( this.Functions.SetHTTPRequestGetOrPostParameter4 )( this.ObjectAddress, hRequest, pchParamName, pchParamValue ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSendHTTPRequestUU( IntPtr thisptr, UInt32 hRequest, ref UInt64 pCallHandle );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool SendHTTPRequest( UInt32 hRequest, ref UInt64 pCallHandle ) 
		{
			return this.GetFunction<NativeSendHTTPRequestUU>( this.Functions.SendHTTPRequest5 )( this.ObjectAddress, hRequest, ref pCallHandle ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeDeferHTTPRequestU( IntPtr thisptr, UInt32 hRequest );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool DeferHTTPRequest( UInt32 hRequest ) 
		{
			return this.GetFunction<NativeDeferHTTPRequestU>( this.Functions.DeferHTTPRequest6 )( this.ObjectAddress, hRequest ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativePrioritizeHTTPRequestU( IntPtr thisptr, UInt32 hRequest );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool PrioritizeHTTPRequest( UInt32 hRequest ) 
		{
			return this.GetFunction<NativePrioritizeHTTPRequestU>( this.Functions.PrioritizeHTTPRequest7 )( this.ObjectAddress, hRequest ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetHTTPResponseHeaderSizeUSU( IntPtr thisptr, UInt32 hRequest, StringBuilder pchHeaderName, ref UInt32 unResponseHeaderSize );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool GetHTTPResponseHeaderSize( UInt32 hRequest, StringBuilder pchHeaderName, ref UInt32 unResponseHeaderSize ) 
		{
			return this.GetFunction<NativeGetHTTPResponseHeaderSizeUSU>( this.Functions.GetHTTPResponseHeaderSize8 )( this.ObjectAddress, hRequest, pchHeaderName, ref unResponseHeaderSize ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetHTTPResponseHeaderValueUSBU( IntPtr thisptr, UInt32 hRequest, StringBuilder pchHeaderName, Byte[] pHeaderValueBuffer, UInt32 uBufferSize );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool GetHTTPResponseHeaderValue( UInt32 hRequest, StringBuilder pchHeaderName, Byte[] pHeaderValueBuffer ) 
		{
			return this.GetFunction<NativeGetHTTPResponseHeaderValueUSBU>( this.Functions.GetHTTPResponseHeaderValue9 )( this.ObjectAddress, hRequest, pchHeaderName, pHeaderValueBuffer, (UInt32) pHeaderValueBuffer.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetHTTPResponseBodySizeUU( IntPtr thisptr, UInt32 hRequest, ref UInt32 unBodySize );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool GetHTTPResponseBodySize( UInt32 hRequest, ref UInt32 unBodySize ) 
		{
			return this.GetFunction<NativeGetHTTPResponseBodySizeUU>( this.Functions.GetHTTPResponseBodySize10 )( this.ObjectAddress, hRequest, ref unBodySize ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetHTTPResponseBodyDataUBU( IntPtr thisptr, UInt32 hRequest, Byte[] pBodyDataBuffer, UInt32 unBufferSize );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool GetHTTPResponseBodyData( UInt32 hRequest, Byte[] pBodyDataBuffer ) 
		{
			return this.GetFunction<NativeGetHTTPResponseBodyDataUBU>( this.Functions.GetHTTPResponseBodyData11 )( this.ObjectAddress, hRequest, pBodyDataBuffer, (UInt32) pBodyDataBuffer.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeReleaseHTTPRequestU( IntPtr thisptr, UInt32 hRequest );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool ReleaseHTTPRequest( UInt32 hRequest ) 
		{
			return this.GetFunction<NativeReleaseHTTPRequestU>( this.Functions.ReleaseHTTPRequest12 )( this.ObjectAddress, hRequest ); 
		}
		
	};
}
