// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class ISteamContentServer001VTable
	{
		public IntPtr LogOn0;
		public IntPtr LogOff1;
		public IntPtr LoggedOn2;
		public IntPtr SendClientContentAuthRequest3;
		private IntPtr DTorISteamContentServer0014;
	};
	
	[InteropHelp.InterfaceVersion("SteamContentServer001")]
	public class ISteamContentServer001 : InteropHelp.NativeWrapper<ISteamContentServer001VTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeLogOnU( IntPtr thisptr, UInt32 a );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool LogOn( UInt32 a ) 
		{
			return this.GetFunction<NativeLogOnU>( this.Functions.LogOn0 )( this.ObjectAddress, a ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeLogOff( IntPtr thisptr );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool LogOff(  ) 
		{
			return this.GetFunction<NativeLogOff>( this.Functions.LogOff1 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeLoggedOn( IntPtr thisptr );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool LoggedOn(  ) 
		{
			return this.GetFunction<NativeLoggedOn>( this.Functions.LoggedOn2 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSendClientContentAuthRequestCU( IntPtr thisptr, UInt64 steamId, UInt32 a );
		public void SendClientContentAuthRequest( CSteamID steamId, UInt32 a ) 
		{
			this.GetFunction<NativeSendClientContentAuthRequestCU>( this.Functions.SendClientContentAuthRequest3 )( this.ObjectAddress, steamId.ConvertToUint64(), a ); 
		}
		
	};
}
