// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class ISteamRemoteStorage003VTable
	{
		public IntPtr FileWrite0;
		public IntPtr FileRead1;
		public IntPtr FileForget2;
		public IntPtr FileDelete3;
		public IntPtr FileShare4;
		public IntPtr FileExists5;
		public IntPtr FilePersisted6;
		public IntPtr GetFileSize7;
		public IntPtr GetFileTimestamp8;
		public IntPtr GetFileCount9;
		public IntPtr GetFileNameAndSize10;
		public IntPtr GetQuota11;
		public IntPtr IsCloudEnabledForAccount12;
		public IntPtr IsCloudEnabledThisApp13;
		public IntPtr SetCloudEnabledThisApp14;
		public IntPtr UGCDownload15;
		public IntPtr GetUGCDetails16;
		public IntPtr UGCRead17;
		public IntPtr GetCachedUGCCount18;
		public IntPtr GetCachedUGCHandle19;
		private IntPtr DTorISteamRemoteStorage00320;
	};
	
	public class ISteamRemoteStorage003 : InteropHelp.NativeWrapper<ISteamRemoteStorage003VTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileWriteSBI( IntPtr thisptr, string pchFile, Byte[] pvData, Int32 cubData );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool FileWrite( string pchFile, Byte[] pvData ) 
		{
			return this.GetFunction<NativeFileWriteSBI>( this.Functions.FileWrite0 )( this.ObjectAddress, pchFile, pvData, (Int32) pvData.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeFileReadSBI( IntPtr thisptr, string pchFile, Byte[] pvData, Int32 cubDataToRead );
		public Int32 FileRead( string pchFile, Byte[] pvData ) 
		{
			return this.GetFunction<NativeFileReadSBI>( this.Functions.FileRead1 )( this.ObjectAddress, pchFile, pvData, (Int32) pvData.Length ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileForgetS( IntPtr thisptr, string pchFile );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool FileForget( string pchFile ) 
		{
			return this.GetFunction<NativeFileForgetS>( this.Functions.FileForget2 )( this.ObjectAddress, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileDeleteS( IntPtr thisptr, string pchFile );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool FileDelete( string pchFile ) 
		{
			return this.GetFunction<NativeFileDeleteS>( this.Functions.FileDelete3 )( this.ObjectAddress, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativeFileShareS( IntPtr thisptr, ref UInt64 retarg, string pchFile );
		public UInt64 FileShare( string pchFile ) 
		{
			UInt64 ret = 0; this.GetFunction<NativeFileShareS>( this.Functions.FileShare4 )( this.ObjectAddress, ref ret, pchFile ); return (UInt64)ret;
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFileExistsS( IntPtr thisptr, string pchFile );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool FileExists( string pchFile ) 
		{
			return this.GetFunction<NativeFileExistsS>( this.Functions.FileExists5 )( this.ObjectAddress, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeFilePersistedS( IntPtr thisptr, string pchFile );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool FilePersisted( string pchFile ) 
		{
			return this.GetFunction<NativeFilePersistedS>( this.Functions.FilePersisted6 )( this.ObjectAddress, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetFileSizeS( IntPtr thisptr, string pchFile );
		public Int32 GetFileSize( string pchFile ) 
		{
			return this.GetFunction<NativeGetFileSizeS>( this.Functions.GetFileSize7 )( this.ObjectAddress, pchFile ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int64 NativeGetFileTimestampS( IntPtr thisptr, ref UInt64 retarg, string pchFile );
		public Int64 GetFileTimestamp( string pchFile ) 
		{
			UInt64 ret = 0; this.GetFunction<NativeGetFileTimestampS>( this.Functions.GetFileTimestamp8 )( this.ObjectAddress, ref ret, pchFile ); return (Int64)ret;
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetFileCount( IntPtr thisptr );
		public Int32 GetFileCount(  ) 
		{
			return this.GetFunction<NativeGetFileCount>( this.Functions.GetFileCount9 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate string NativeGetFileNameAndSizeII( IntPtr thisptr, Int32 iFile, ref Int32 pnFileSizeInBytes );
		public string GetFileNameAndSize( Int32 iFile, ref Int32 pnFileSizeInBytes ) 
		{
			return InteropHelp.DecodeANSIReturn( this.GetFunction<NativeGetFileNameAndSizeII>( this.Functions.GetFileNameAndSize10 )( this.ObjectAddress, iFile, ref pnFileSizeInBytes ) ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeGetQuotaII( IntPtr thisptr, ref Int32 pnTotalBytes, ref Int32 puAvailableBytes );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool GetQuota( ref Int32 pnTotalBytes, ref Int32 puAvailableBytes ) 
		{
			return this.GetFunction<NativeGetQuotaII>( this.Functions.GetQuota11 )( this.ObjectAddress, ref pnTotalBytes, ref puAvailableBytes ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsCloudEnabledForAccount( IntPtr thisptr );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool IsCloudEnabledForAccount(  ) 
		{
			return this.GetFunction<NativeIsCloudEnabledForAccount>( this.Functions.IsCloudEnabledForAccount12 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeIsCloudEnabledThisApp( IntPtr thisptr );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool IsCloudEnabledThisApp(  ) 
		{
			return this.GetFunction<NativeIsCloudEnabledThisApp>( this.Functions.IsCloudEnabledThisApp13 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate bool NativeSetCloudEnabledThisAppB( IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bEnable );
		[return: MarshalAs(UnmanagedType.I1)]
		public bool SetCloudEnabledThisApp( bool bEnable ) 
		{
			return this.GetFunction<NativeSetCloudEnabledThisAppB>( this.Functions.SetCloudEnabledThisApp14 )( this.ObjectAddress, bEnable ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeUGCDownloadII( IntPtr thisptr, Int32 unk1, Int32 unk2 );
		public Int32 UGCDownload( Int32 unk1, Int32 unk2 ) 
		{
			return this.GetFunction<NativeUGCDownloadII>( this.Functions.UGCDownload15 )( this.ObjectAddress, unk1, unk2 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetUGCDetailsIIIIII( IntPtr thisptr, Int32 unk1, Int32 unk2, Int32 unk3, Int32 unk4, Int32 unk5, Int32 unk6 );
		public Int32 GetUGCDetails( Int32 unk1, Int32 unk2, Int32 unk3, Int32 unk4, Int32 unk5, Int32 unk6 ) 
		{
			return this.GetFunction<NativeGetUGCDetailsIIIIII>( this.Functions.GetUGCDetails16 )( this.ObjectAddress, unk1, unk2, unk3, unk4, unk5, unk6 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeUGCReadIIII( IntPtr thisptr, Int32 unk1, Int32 unk2, Int32 unk3, Int32 unk4 );
		public Int32 UGCRead( Int32 unk1, Int32 unk2, Int32 unk3, Int32 unk4 ) 
		{
			return this.GetFunction<NativeUGCReadIIII>( this.Functions.UGCRead17 )( this.ObjectAddress, unk1, unk2, unk3, unk4 ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCachedUGCCount( IntPtr thisptr );
		public Int32 GetCachedUGCCount(  ) 
		{
			return this.GetFunction<NativeGetCachedUGCCount>( this.Functions.GetCachedUGCCount18 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCachedUGCHandle( IntPtr thisptr );
		public Int32 GetCachedUGCHandle(  ) 
		{
			return this.GetFunction<NativeGetCachedUGCHandle>( this.Functions.GetCachedUGCHandle19 )( this.ObjectAddress ); 
		}
		
	};
}
