// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	public enum ERemoteStorageFileRoot : int
	{
		k_ERemoteStorageFileRootInvalid = -1,
		k_ERemoteStorageFileRootDefault = 0,
		k_ERemoteStorageFileRootGameInstall = 1,
		k_ERemoteStorageFileRootWinMyDocuments = 2,
		k_ERemoteStorageFileRootWinAppDataLocal = 3,
		k_ERemoteStorageFileRootWinAppDataRoaming = 4,
		k_ERemoteStorageFileRootSteamUserBaseStorage = 5,
		k_ERemoteStorageFileRootMacHome = 6,
		k_ERemoteStorageFileRootMacAppSupport = 7,
		k_ERemoteStorageFileRootMacDocuments = 8,
		k_ERemoteStorageFileRootMax = 9,
	};
	
	public enum ERemoteStorageSyncState : int
	{
		k_ERemoteSyncStateDisabled = 0,
		k_ERemoteSyncStateUnknown = 1,
		k_ERemoteSyncStateSynchronized = 2,
		k_ERemoteSyncStateSyncInProgress = 3,
		k_ERemoteSyncStatePendingChangesInCloud = 4,
		k_ERemoteSyncStatePendingChangesLocally = 5,
		k_ERemoteSyncStatePendingChangesInCloudAndLocally = 6,
		k_ERemoteSyncStateConflictingChanges = 7,
	};
	
	public enum EUCMFilePrivacyState : int
	{
		k_EUCMFilePrivacyStateInvalid = -1,
		k_EUCMFilePrivacyStateUnpublished = 0,
		k_EUCMFilePrivacyStatePublished = 1,
		k_EUCMFilePrivacyStatePrivate = 2,
		k_EUCMFilePrivacyStateFriendsOnly = 4,
		k_EUCMFilePrivacyStatePublic = 8,
		k_EUCMFilePrivacyStateAll = 14,
	};
	
	public enum ERemoteStoragePlatform : int
	{
		k_ERemoteStoragePlatformNone = 0,
		k_ERemoteStoragePlatformWindows = 1,
		k_ERemoteStoragePlatformOSX = 2,
		k_ERemoteStoragePlatformPS3 = 4,
		k_ERemoteStoragePlatformReserved1 = 8,
		k_ERemoteStoragePlatformReserved2 = 16,
		k_ERemoteStoragePlatformAll = -1,
	};
	
	public enum EResolveConflict : int
	{
		k_EResolveConflictKeepClient = 1,
		k_EResolveConflictKeepServer = 2,
	};
	
	public enum ERemoteStoragePublishedFileVisibility : int
	{
	};
	
	public enum ERemoteStoragePublishedFileSortOrder : int
	{
	};
	
	public enum EWorkshopFileType : int
	{
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct SteamParamStringArray_t
	{
		public Int32 iPadding;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct RemoteStorageUpdatePublishedFileRequest_t
	{
		public Int32 iPadding;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1301)]
	public struct RemoteStorageAppSyncedClient_t
	{
		public const int k_iCallback = 1301;
		public UInt32 m_nAppID;
		public EResult m_eResult;
		public Int32 m_unNumDownloads;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1302)]
	public struct RemoteStorageAppSyncedServer_t
	{
		public const int k_iCallback = 1302;
		public UInt32 m_nAppID;
		public EResult m_eResult;
		public Int32 m_unNumUploads;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1303)]
	public struct RemoteStorageAppSyncProgress_t
	{
		public const int k_iCallback = 1303;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
		public string m_rgchCurrentFile;
		public UInt32 m_nAppID;
		public UInt32 m_uBytesTransferredThisChunk;
		public double m_dAppPercentComplete;
		[MarshalAs(UnmanagedType.I1)]
		public bool m_bUploading;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1304)]
	public struct RemoteStorageAppInfoLoaded_t
	{
		public const int k_iCallback = 1304;
		public UInt32 m_nAppID;
		public EResult m_eResult;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1305)]
	public struct RemoteStorageAppSyncStatusCheck_t
	{
		public const int k_iCallback = 1305;
		public UInt32 m_nAppID;
		public EResult m_eResult;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1306)]
	public struct RemoteStorageConflictResolution_t
	{
		public const int k_iCallback = 1306;
		public UInt32 m_nAppID;
		public EResult m_eResult;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1307)]
	public struct RemoteStorageFileShareResult_t
	{
		public const int k_iCallback = 1307;
		public EResult m_eResult;
		public UInt64 m_hFile;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1308)]
	public struct Deprecated_RemoteStorageDownloadUGCResult_t
	{
		public const int k_iCallback = 1308;
		public EResult m_eResult;
		public UInt64 m_hFile;
		public UInt32 m_nAppID;
		public Int32 m_nSizeInBytes;
		public string m_pchFileName;
		public UInt64 m_ulSteamIDOwner;
	};
	
	[StructLayout(LayoutKind.Sequential,Pack=8)]
	[InteropHelp.CallbackIdentity(1317)]
	public struct RemoteStorageDownloadUGCResult_t
	{
		public const int k_iCallback = 1317;
		public EResult m_eResult;
		public UInt64 m_hFile;
		public UInt32 m_nAppID;
		public Int32 m_nSizeInBytes;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
		public string m_pchFileName;
		public UInt64 m_ulSteamIDOwner;
	};
	
}
