// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamSubscriptionReceipt
	{
		ESteamSubscriptionStatus eStatus;
		ESteamSubscriptionStatus ePreviousStatus;
		ESteamSubscriptionBillingInfoType eReceiptInfoType;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 23)]
		string szConfirmationCode;
	};
	
}
