// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamApp
	{
		public IntPtr szName;
		public UInt32 uMaxNameChars;
		public IntPtr szLatestVersionLabel;
		public UInt32 uMaxLatestVersionLabelChars;
		public IntPtr szCurrentVersionLabel;
		public UInt32 uMaxCurrentVersionLabelChars;
		public IntPtr szInstallDirName;
		public UInt32 uMaxInstallDirNameChars;
		public UInt32 uId;
		public UInt32 uLatestVersionId;
		public UInt32 uCurrentVersionId;
		public UInt32 uMinCacheFileSizeMB;
		public UInt32 uMaxCacheFileSizeMB;
		public UInt32 uNumLaunchOptions;
		public UInt32 uNumIcons;
		public UInt32 uNumVersions;
		public UInt32 uNumDependencies;
		public IntPtr szUnkString;
	};
	
}
