// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamSubscriptionStats
	{
		UInt32 uNumSubscriptions;
		UInt32 uMaxNameChars;
		UInt32 uMaxApps;
	};
	
}
